### ISSUE TITLE
Error deploying tcp-to-blob [/dist/bundle' doesn't exist.]

### ISSUE THREAD

**Issue by mattweale** [Azure/azure-orbital-integration#178] opened 2022-11-29 17:55 UTC
![tcp-to-blob-error](https://user-images.githubusercontent.com/51047506/204605932-1e919a71-6392-426a-8235-890404725808.png)

This has worked fine until about 4 weeks ago and now I consistently get this error, have tried both WLS locally or Azure Cloud Shell, error is consistent.

$ yarn docker-push && yarn deploy-fast
$ DOCKER_TAG='tcp-to-blob:latest';DOCKER_FILE='./deploy/Dockerfile';. ./deploy/build_and_publish_image.sh;
/bin/sh: 6: ./deploy/build_and_publish_image.sh: [[: not found
/bin/sh: 10: ./deploy/build_and_publish_image.sh: [[: not found
Adding "tcp-to-blob:latest" image to "aoit2bmcapaquademoacr" ACR.
'./dist/bundle' doesn't exist.

**Comment by micholas** [comment] 2022-12-02 03:39
This was fixed by: https://github.com/Azure/azure-orbital-integration/pull/176

FYI, here is a GitHub issue associated with the root cause: https://github.com/microsoft/TypeScript/issues/51567

**Closed by micholas** 2022-12-02 03:39 UTC
